name: SpoutBackpack
version: 2.3.1
description: Give your players a Backpack w/ Spout.
author: NeatMonster
website: http://craftisland.no-ip.org/
dev-url: http://dev.bukkit.org/server-mods/spoutbackpack/
main: me.neatmonster.spoutbackpack.SpoutBackpack
database: false
depend: [Spout]
softdepend: [Permissions, PermissionsBukkit, GroupManager, iConomy, BOSEconomy, Essentials Economy, MultiCurrency, WorldGuard, MobArena, Jail]
commands:
    backpack:
        description: Main command of SpoutBackpack.
    bp:
        description: Alias of /backpack.